### ISSUE TITLE
Bug in TrueTypeFontFile readGLYFTable causing overflow

### ISSUE THREAD

**Issue by KiwiWilkinson** [SimpleApp/PDFParser#5]
Line 312 is:

`_ = r.seek(pos: Int(glyfTableIndex.offset) + Int(offset * 2))`

However in this part of the case *offset* is a *short*, so this overflows for offsets > 32767.

To stop the overflow this should be corrected to

`_ = r.seek(pos: Int(glyfTableIndex.offset) + (Int(offset) * 2))`

**Comment by SimpleApp** [comment]
Fixed
