### ISSUE TITLE
Support for mulicolumn pdfs

### ISSUE THREAD

**Issue by appfrilans** [SimpleApp/PDFParser#6]
Can you point me to how to add support for mulicolumn pdfs?

If there is more than one column, is seems as the framework merges these my line. The y-coordinate is correct but the x-coordnate could overlap for letters that are in different columns but on the same line.

**Comment by SimpleApp** [comment]
HI, i'm absolutely sorry to only reply now, but for some reason i hadn't received any notification from github. I suppose you've solved your problem by now, in case you haven't (or for others reading this issue) : 

Supporting complex layouts is actually the hard part of pdf mining. It is based on a lot of heuristics about what a text layout should look like in general, and infer which text block should be associated together based on their spacing (and the other spacing around them). 

PDFParser offers a very simple one-column layout example with the file at : PDFParser/result/SimpleDocumentIndexer.swift
It receives textblocks from the parser, and associate them to form words, assuming the layout is a one column.

If you want to support multicolumn, you'll have to build your own implementation of a DocumentIndexer (protocol is defined in the DocumentIndexer.swift file) and pass it to the PDFParser at init.
